pasture/urls.py
from django.contrib import admin
from django.urls import path, include
from restaurant import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('allauth.urls')),
    path('book/', views.book, name='book'),
    path('my_profile/', views.my_profile, name='my_profile'),
    path('edit/<booking_id>', views.edit_booking, name='edit'),
    path('delete/<booking_id>', views.delete_booking, name='delete_booking'),
    path('staff_profile/', views.staff_profile, name='staff_profile'),
    path('manage_bookings/', views.manage_bookings, name='manage_bookings'),
    path('menu/', views.menu, name='menu'),
    path('manage_menus/', views.manage_menus, name='manage_menus'),
    path('edit_menu/<menu_id>', views.edit_menu, name='edit_menu'),
    path('delete_menu/<menu_id>', views.delete_menu, name='delete_menu'),
]

restaurant/models.py
from django.db import models
from django.contrib.auth.models import User


# List of times available to book when making a reservation
TIMES = (
    (1, '12:00-13:50'),
    (2, '14:00-15:50'),
    (3, '16:00-17:50'),
    (4, '18:00-19:50'),
    (5, '20:00-21:50')
)


TYPES = (
    (1, 'Starter'),
    (2, 'Main'),
    (3, 'Dessert'),
    (4, 'Side'),
    (5, 'Sauce'),
)


class Booking(models.Model):
    """
    Model to store data regarding booking reservations
    """
    username = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="booking"
    )
    name = models.CharField(max_length=80)
    phone_no = models.CharField(max_length=11, default=0)
    date = models.DateField()
    time = models.IntegerField(choices=TIMES, default=1)
    no_of_guests = models.IntegerField(default=1)
    notes = models.TextField(blank=True)


    class Meta:
        """
        Ensure that the table cannot be double booked
        """
        constraints = [
            models.UniqueConstraint(fields=['date', 'time'], name='unique_booking'),
        ]


class Menu(models.Model):
    """ 
    Model to store data regarding menu items
    """
    type = models.IntegerField(choices=TYPES)
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    price = models.FloatField()

templates/base.html
{% load static %}
{% load active_link_tags %}

<!DOCTYPE html>
<html class="h-100">

<head>     
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Galada&family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/d8bc5721cb.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">   
    {% block title %}
    <!-- Title Goes here -->
    {% endblock title %}
</head>

<body class="d-flex flex-column h-100"> 
    <div class="container fixed-top z-3">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div> 
                {% endfor %}
            </div>
        </div>
    </div>      
    <!-- Header -->
    <header class="header fixed-top d-flex mb-3 z-0">       
        <!-- Logo -->
        <div class="logo-container me-auto px-3 px-lg-5 my-2 my-lg-4 d-block align-items-start">
            <img src="https://res.cloudinary.com/dkxdppkpe/image/upload/v1701084882/logo_sqdz3b.webp" alt="Pasture Logo" id="logo">     
        </div>   
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg align-items-center">
            <div class="container-fluid">
                <button class="navbar-toggler white" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">
                        <i class="fas fa-bars white"></i>
                    </span>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header justify-content-end">
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <a class="nav-link {% active_link 'home' 'active' strict=True %}" href="{% url 'home' %}">Home</a>
                            </li>      
                            <li class="nav-item">
                                <a class="nav-link {% active_link 'menu' 'active' %}" href="{% url 'menu' %}">Menu</a>
                            </li> 
                            <li class="nav-item">
                                <a class="nav-link {% active_link 'book' 'active' %}" href="{% url 'book' %}">Book</a>
                            </li> 
                            {% if user.is_authenticated %}  
                                {% if request.user.is_staff %}
                                <li class="nav-item">
                                    <a class="nav-link {% active_link 'staff_management' 'active' %}" href="{% url 'staff_profile' %}">Staff Management</a>
                                </li>   
                                {% else %}                                
                                <li class="nav-item">
                                    <a class="nav-link {% active_link 'my_profile' 'active' %}" href="{% url 'my_profile' %}">My Profile</a>
                                </li> 
                                {% endif %}
                            <li class="nav-item">
                                <a class="nav-link {% active_link 'account_logout' 'active' %}" href="{% url 'account_logout' %}">Logout</a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link {% active_link 'account_signup' 'active' %}" href="{% url 'account_signup' %}">Register</a>
                            </li>       
                            <li class="nav-item">
                                <a class="nav-link {% active_link 'account_login' 'active' %}" href="{% url 'account_login' %}">Login</a>
                            </li>  
                            {% endif %}  
                        </ul>            
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <!-- Main Content Section -->
    <main class="main-content">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>
    <!-- Footer -->
    <footer class="footer d-flex justify-content-between flex-wrap flex-xl-nowrap mt-auto py-5 px-3 px-lg-5 white">
        <div class="col-12 col-md-6 col-lg-4 pb-4 pb-lg-0">
            <h2>Find Us</h2>
            <address>
                The Gatehouse<br>
                Church Lane<br> 
                Chipping Sodbury<br>
                BS37 9PD<br>
            </address>
        </div>
        <div class="col-12 col-md-6 col-lg-4 text-lg-center pb-4 pb-lg-0">
            <h2>Contact Us</h2>
            <p>Email: <a href="mailto:hello@pasture.co.uk" class="white">hello@pasture.co.uk</a><br>
            Tel: 01454 723 0475</p>
        </div>
        <div class="col-12 col-md-12 col-lg-4 text-lg-end">
            <h2>Opening Times</h2>
            <p>
                Mon - Sun: 12pm - 11pm
            </p>
        </div>
    </footer>
    <!-- Javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/book.html
{% extends "base.html" %}
{% block title %}
    <title>Pasture | Book a Table</title>  
{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
    <!-- Hero Image  -->
    <section class="generic-img d-flex justify-content-center align-items-end text-center white">
        <div class="title-panel p-5">
            <h1>Book a Table</h1>            
        </div>
    </section>
    <!-- Content Area -->
    <section class="text-area">
        {% if user.is_authenticated %}
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-8 offset-md-2">
                    <h2 class="red">Hello {{ user.username }}</h2>
                    <p>Please complete the form below to make a reservation.</p>
                    <!-- Booking Form-->                
                    <form method="post">
                        {{ booking_form | crispy }}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-signup btn-lg">Submit</button> 
                    </form>
                </div>
            </div>
        </div>        
        {% else %}
        <p class="text-center">To book a table, please <a href="{% url 'account_signup' %}">register</a> or if you already have an account, please <a href="{% url 'account_login' %}">login</a>.</p>
        {% endif %}
    </section>
{%endblock%}

templates/delete_booking.html
{% extends "base.html" %}
{% block title %}
    <title>Pasture | Delete Booking</title>  
{% endblock title %}

{% block content %}
    <!-- Hero Image  -->
    <section class="generic-img d-flex justify-content-center align-items-end text-center white">
        <div class="title-panel p-5">
            <h1>Delete Booking</h1>            
        </div>
    </section>
    <!-- Content Area -->
    <section class="text-area profile">
        {% if user.is_authenticated %}
        <div class="container-fluid">          
            <form method="POST">
                {% csrf_token %}
                Are you sure you want to delete this reservation?
                <input type="submit" value="Yes" class="btn btn-danger btn-lg px-5">
                <a href="{% url 'my_profile' %}">Cancel</a>
            </form>
        </div>        
        {% else %}
        <p class="text-center">You must <a href="{% url 'account_login' %}">login</a> to view this page.</p>
        {% endif %}
    </section>
{%endblock%}

templates/delete_menu.html
{% extends "base.html" %}
{% block title %}
    <title>Pasture | Delete Menu</title>  
{% endblock title %}

{% block content %}
    <!-- Hero Image  -->
    <section class="generic-img d-flex justify-content-center align-items-end text-center white">
        <div class="title-panel p-5">
            <h1>Delete Menu</h1>            
        </div>
    </section>
    <!-- Content Area -->
    <section class="text-area profile">
        {% if request.user.is_staff %}
        <div class="container-fluid">          
            <form method="POST">
                {% csrf_token %}
                Are you sure you want to delete this menu item?
                <input type="submit" value="Yes" class="btn btn-danger btn-lg px-5">
                <a href="{% url 'manage_menus' %}">Cancel</a>
            </form>
        </div>        
        {% else %}
        <p class="text-center">You must be a member of staff and <a href="{% url 'account_login' %}">login</a> to view this page.</p>
        {% endif %}
    </section>
{%endblock%}

templates/edit_booking.html
{% extends "base.html" %}
{% block title %}
    <title>Pasture | Edit Booking</title>  
{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
    <!-- Hero Image  -->
    <section class="generic-img d-flex justify-content-center align-items-end text-center white">
        <div class="title-panel p-5">
            <h1>Edit Booking</h1>            
        </div>
    </section>
    <!-- Content Area -->
    <section class="text-area profile">
        {% if user.is_authenticated %}
        <div class="container-fluid">                                        
            <p>Please make any changes to the reservation using the form below.</p>
                <!-- Booking Form-->                
                <form method="post">
                    {{ form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Edit</button> 
                </form>
        </div>        
        {% else %}
        <p class="text-center">You must <a href="{% url 'account_login' %}">login</a> to view this page.</p>
        {% endif %}
    </section>
{%endblock%}

templates/edit_menu.html
{% extends "base.html" %}
{% block title %}
    <title>Pasture | Edit Menu</title>  
{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
    <!-- Hero Image  -->
    <section class="generic-img d-flex justify-content-center align-items-end text-center white">
        <div class="title-panel p-5">
            <h1>Edit Menu</h1>            
        </div>
    </section>
    <!-- Content Area -->
    <section class="text-area profile">
        {% if request.user.is_staff %}
        <div class="container-fluid">                                        
            <p>Please make any changes to the menu item using the form below.</p>
                <!-- Menu Form-->                
                <form method="post">
                    {{ form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Edit</button> 
                </form>
        </div>        
        {% else %}
        <p class="text-center">You must be a member of staff and <a href="{% url 'account_login' %}">login</a> to view this page.</p>
        {% endif %}
    </section>
{%endblock%}

templates/index.html
{% extends "base.html" %}
{% block title %}
    <title>Pasture | Home</title>  
{% endblock title %}

{% block content %}
<!-- Hero Image  -->
<section class="hero-img d-flex justify-content-center align-items-center text-center white">
    <div class="welcome-panel p-5">
        <h1>Welcome to Pasture</h1>
        <ul class="links d-md-flex justify-content-center mt-4">
            <li><a href="{% url 'menu' %}" class="white">View Menu</a></li>
            <li><a href="{% url 'book' %}" class="white">Book a Table</a></li>
        </ul>
    </div>
</section>
<!-- Text Area -->
<section class="text-area text-center">
    <p>Pasture is a family run restaurant situated on the edge of the Cotswolds, the perfect setting to relax, unwind and experience our mouth watering dishes.</p>
    <p>All of our beef is carefully selected from local butchers to bring you the perfect steak, together with seasonal vegetables grown in our own kitchen garden.</p>
    <p>We have a fabulous wine list together with a great selection of ales so why not <a href="{% url 'book' %}" class="red">book a table</a> today.</p>
</section>
{%endblock%}

templates/manage_bookings.html
{% extends "base.html" %}
{% load active_link_tags %}
{% block title %}
    <title>Pasture | Manage Bookings</title>  
{% endblock title %}

{% block content %}
    <!-- Hero Image  -->
    <section class="generic-img d-flex justify-content-center align-items-end text-center white">
        <div class="title-panel p-5">
            <h1>Manage Bookings</h1>            
        </div>
    </section>
    <!-- Content Area -->
    <section class="text-area profile">
        {% if request.user.is_staff %}
        <div class="container-fluid">   
            <!-- Sub Navigation -->
            <div class="d-flex justify-content-end pb-5">                
                <ul class="d-flex sub-nav">
                    <li><a href="{% url 'manage_bookings' %}" class="red px-5 {% active_link 'manage_bookings' 'active' strict=True %}">Manage Bookings</a></li>
                    <li><a href="{% url 'manage_menus' %}" class="red {% active_link 'manage_menus' 'active' strict=True %}">Manage Menus</a></li>
                </ul>
            </div>  
            <!-- Filter -->
            <div class="d-flex border-bottom border-4 mb-5 pb-2">
                <p class="pe-5">Filter bookings by Name or Date:</p>
                <form method="GET" class="filter-form pb-5">
                    {{ booking_filter.form.name }}
                    {{ booking_filter.form.date }}
                    <button class="btn btn-lg" type="submit">Search</button>
                </form>  
            </div>                         
            <!-- All reservations -->   
            <div class="d-none d-xxl-flex row mt-5">
                <div class="col-xxl-3">
                    <p><strong>Name</strong></p>
                </div>
                <div class="col-xxl-1">
                    <p><strong>Date</strong></p>
                </div>
                <div class="col-xxl-2">
                    <p><strong>Time</strong></p>
                </div>
                <div class="col-xxl-1">
                    <p><strong>No. of Guests</strong></p>
                </div>
                <div class="col-xxl-3">
                    <p><strong>Notes</strong></p>
                </div>
            </div>
            {% for booking in all_bookings %}
            <div class="row border-top border-2 mt-2 pt-4">
                <div class="col-12 col-xxl-3">
                    <p><span class="d-xxl-none"><strong>Name:</strong></span> {{ booking.name }}</p>
                </div>
                <div class="col-12 col-xxl-1">
                    <p><span class="d-xxl-none"><strong>Date:</strong></span> {{ booking.date|date:"d/m/y" }}</p>
                </div>
                <div class="col-12 col-xxl-2">
                    <p><span class="d-xl-none"><strong>Time:</strong></span> {{ booking.get_time_display }}</p>
                </div>
                <div class="col-12 col-xxl-1">
                    <p><span class="d-xxl-none"><strong>No. of Guests:</strong></span> {{ booking.no_of_guests }}</p>
                </div>
                <div class="col-12 col-xxl-3">
                    <p><span class="d-xl-none"><strong>Notes:</strong></span> {{ booking.notes }}</p>
                </div>
                <div class="col-3 col-xxl-1">
                    <p><a href="/edit/{{ booking.id }}">Edit</a></p>
                </div>
                <div class="col-3 col-xxl-1">
                    <p><a href="/delete/{{ booking.id }}" class="red">Delete</a></p>
                </div>
            </div>
            {% endfor %}
        </div>        
        {% else %}
        <p class="text-center">You must be a member of staff and <a href="{% url 'account_login' %}">login</a> to view this page.</p>
        {% endif %}
    </section>
{%endblock%}

templates/menu.html
{% extends "base.html" %}
{% block title %}
    <title>Pasture | Menu</title>  
{% endblock title %}

{% block content %}
    <!-- Hero Image  -->
    <section class="generic-img d-flex justify-content-center align-items-end text-center white">
        <div class="title-panel p-5">
            <h1>Menu</h1>            
        </div>
    </section>
    <!-- Content Area -->
    <section class="text-area">
        <!-- Starters Menu Items -->    
        <div class="container mb-5">
            <h2 class="red text-center">Starters</h2>
            {% for starter in starters %}
            <div class="row">
                <div class="col-8">
                    <h3>{{ starter.title }}</h3>
                    <p class="small"><i>{{ starter.description }}</i></p>
                </div>
                <div class="col-2 offset-2">
                    <p>£{{ starter.price|floatformat:2 }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- Mains Menu Items -->    
        <div class="container mb-5">
            <h2 class="red text-center">Mains</h2>   
            {% for main in mains %}
            <div class="row">
                <div class="col-8">
                    <h3>{{ main.title }}</h3>
                    <p class="small"><i>{{ main.description }}</i></p>
                </div>
                <div class="col-2 offset-2">
                    <p>£{{ main.price|floatformat:2 }}</p>
                </div>
            </div>
            {% endfor %}
        </div>  
         <!-- Sides Menu Items -->   
         <div class="container mb-5">
            <h2 class="red text-center">Sides</h2>  
            {% for side in sides %}
            <div class="row">
                <div class="col-8">
                    <h3>{{ side.title }}</h3>
                    <p class="small"><i>{{ side.description }}</i></p>
                </div>
                <div class="col-2 offset-2">
                    <p>£{{ side.price|floatformat:2 }}</p>
                </div>
            </div>
            {% endfor %}
        </div>  
         <!-- Sauces Menu Items -->   
         <div class="container mb-5">
            <h2 class="red text-center">Sauces</h2>  
            {% for sauce in sauces %}
            <div class="row">
                <div class="col-8">
                    <h3>{{ sauce.title }}</h3>
                    <p class="small"><i>{{ sauce.description }}</i></p>
                </div>
                <div class="col-2 offset-2">
                    <p>£{{ sauce.price|floatformat:2 }}</p>
                </div>
            </div>
            {% endfor %}
        </div>  
        <!-- Desserts Menu Items -->   
        <div class="container mb-5">
            <h2 class="red text-center">Desserts</h2>  
            {% for dessert in desserts %}
            <div class="row">
                <div class="col-8">
                    <h3>{{ dessert.title }}</h3>
                    <p class="small"><i>{{ dessert.description }}</i></p>
                </div>
                <div class="col-2 offset-2">
                    <p>£{{ dessert.price|floatformat:2 }}</p>
                </div>
            </div>
            {% endfor %}
        </div>  
    </section>
{%endblock%}

templates/my_profile.html
{% extends "base.html" %}
{% block title %}
    <title>Pasture | My Profile</title>  
{% endblock title %}

{% block content %}
    <!-- Hero Image  -->
    <section class="generic-img d-flex justify-content-center align-items-end text-center white">
        <div class="title-panel p-5">
            <h1>My Profile</h1>            
        </div>
    </section>
    <!-- Content Area -->
    <section class="text-area profile">
        {% if user.is_authenticated %}
        <div class="container-fluid">          
            <h2 class="red">Hello {{ user.username }}</h2>
            <p>Welcome to your dashboard where you can view, edit and delete your reservations.</p>
            <div class="d-none d-xxl-flex row mt-5">
                <div class="col-xxl-3">
                    <p><strong>Name</strong></p>
                </div>
                <div class="col-xxl-1">
                    <p><strong>Date</strong></p>
                </div>
                <div class="col-xxl-2">
                    <p><strong>Time</strong></p>
                </div>
                <div class="col-xxl-1">
                    <p><strong>No. of Guests</strong></p>
                </div>
                <div class="col-xxl-3">
                    <p><strong>Notes</strong></p>
                </div>
            </div>
            {% for booking in bookings %}
            <div class="row border-top border-2 mt-2 pt-4">
                <div class="col-12 col-xxl-3">
                    <p><span class="d-xxl-none"><strong>Name:</strong></span> {{ booking.name }}</p>
                </div>
                <div class="col-12 col-xxl-1">
                    <p><span class="d-xxl-none"><strong>Date:</strong></span> {{ booking.date|date:"d/m/y" }}</p>
                </div>
                <div class="col-12 col-xxl-2">
                    <p><span class="d-xl-none"><strong>Time:</strong></span> {{ booking.get_time_display }}</p>
                </div>
                <div class="col-12 col-xxl-1">
                    <p><span class="d-xxl-none"><strong>No. of Guests:</strong></span> {{ booking.no_of_guests }}</p>
                </div>
                <div class="col-12 col-xxl-3">
                    <p><span class="d-xl-none"><strong>Notes:</strong></span> {{ booking.notes }}</p>
                </div>
                <div class="col-3 col-xxl-1">
                    <p><a href="/edit/{{ booking.id }}">Edit</a></p>
                </div>
                <div class="col-3 col-xxl-1">
                    <p><a href="/delete/{{ booking.id }}" class="red">Delete</a></p>
                </div>
            </div>
            {% endfor %}
            <div class="text-center pt-5 border-top border-3 mt-5 pt-2">
                <a href="{% url 'book' %}" class="red">Create New Reservation</a>
            </div>            
        </div>        
        {% else %}
        <p class="text-center">You must <a href="{% url 'account_login' %}">login</a> to view this page.</p>
        {% endif %}
    </section>
{%endblock%}

templates/staff_profile.html
{% extends "base.html" %}
{% load active_link_tags %}
{% block title %}
    <title>Pasture | Staff Management</title>  
{% endblock title %}

{% block content %}
    <!-- Hero Image  -->
    <section class="generic-img d-flex justify-content-center align-items-end text-center white">
        <div class="title-panel p-5">
            <h1>Staff Management Dashboard</h1>            
        </div>
    </section>
    <!-- Content Area -->
    <section class="text-area profile">
        {% if request.user.is_staff %}
        <div class="container-fluid">   
            <!-- Sub Navigation -->
            <div class="d-flex justify-content-between">
                <h2 class="red">Hello {{ user.username }}</h2>
                <ul class="d-flex sub-nav">
                    <li><a href="{% url 'manage_bookings' %}" class="red px-5 {% active_link 'manage_bookings' 'active' strict=True %}">Manage Bookings</a></li>
                    <li><a href="{% url 'manage_menus' %}" class="red {% active_link 'manage_menus' 'active' strict=True %}">Manage Menus</a></li>
                </ul>
            </div>  
            <!-- Today's reservations -->
            <p>Here are the reservations for today:</p>
            {% if bookings %}
                <div class="d-none d-xxl-flex row mt-5">
                    <div class="col-xxl-3">
                        <p><strong>Name</strong></p>
                    </div>
                    <div class="col-xxl-1">
                        <p><strong>Date</strong></p>
                    </div>
                    <div class="col-xxl-2">
                        <p><strong>Time</strong></p>
                    </div>
                    <div class="col-xxl-1">
                        <p><strong>No. of Guests</strong></p>
                    </div>
                    <div class="col-xxl-3">
                        <p><strong>Notes</strong></p>
                    </div>
                </div>
                {% for booking in bookings %}
                    <div class="row border-top border-2 mt-2 pt-4">
                        <div class="col-12 col-xxl-3">
                            <p><span class="d-xxl-none"><strong>Name:</strong></span> {{ booking.name }}</p>
                        </div>
                        <div class="col-12 col-xxl-1">
                            <p><span class="d-xxl-none"><strong>Date:</strong></span> {{ booking.date|date:"d/m/y" }}</p>
                        </div>
                        <div class="col-12 col-xxl-2">
                            <p><span class="d-xl-none"><strong>Time:</strong></span> {{ booking.get_time_display }}</p>
                        </div>
                        <div class="col-12 col-xxl-1">
                            <p><span class="d-xxl-none"><strong>No. of Guests:</strong></span> {{ booking.no_of_guests }}</p>
                        </div>
                        <div class="col-12 col-xxl-3">
                            <p><span class="d-xl-none"><strong>Notes:</strong></span> {{ booking.notes }}</p>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>There are no reservations today.</p>
            {% endif %}
        </div>        
        {% else %}
        <p class="text-center">You must be a member of staff and <a href="{% url 'account_login' %}">login</a> to view this page.</p>
        {% endif %}
    </section>
{%endblock%}